web_home:
    pattern:  /
    defaults: { _controller: WebBundle:Home:home }
web_about:
    pattern:  /nosotros
    defaults: { _controller: WebBundle:About:about }
web_our_services:
    pattern:  /nuestros-servicios
    defaults: { _controller: WebBundle:OurServices:ourServices }
web_our_services_tshirt:
    pattern:  /nuestros-servicios/remeras-estampadas
    defaults: { _controller: WebBundle:OurServices:tshirt }
