web_home:
    pattern:  /
    defaults: { _controller: WebBundle:Home:home }
web_about:
    pattern:  /nosotros
    defaults: { _controller: WebBundle:About:about }

# Our services
web_our_services:
    pattern:  /nuestros-servicios
    defaults: { _controller: WebBundle:OurServices:ourServices }
web_our_services_tshirt:
    pattern:  /nuestros-servicios/remeras-estampadas
    defaults: { _controller: WebBundle:OurServices:tshirt }
web_our_services_keychain_ribbon:
    pattern:  /nuestros-servicios/llaveros-cinta-publicitarios
    defaults: { _controller: WebBundle:OurServices:keychainRibbon }
web_our_services_keychain_poli:
    pattern:  /nuestros-servicios/llaveros-polimero-publicitarios
    defaults: { _controller: WebBundle:OurServices:keychainPoli }
web_our_services_cushion:
    pattern:  /nuestros-servicios/almohadones-publicitarios
    defaults: { _controller: WebBundle:OurServices:cushion }
web_our_services_cover:
    pattern:  /nuestros-servicios/fundas-publicitarias
    defaults: { _controller: WebBundle:OurServices:cover }
web_our_services_bag:
    pattern:  /nuestros-servicios/bolsas-ecologicas-publicitarias
    defaults: { _controller: WebBundle:OurServices:bag }
web_our_services_sweatshirt:
    pattern:  /nuestros-servicios/buzos-estampados
    defaults: { _controller: WebBundle:OurServices:sweatshirt }
web_our_services_dome:
    pattern:  /nuestros-servicios/domes-publicitarios
    defaults: { _controller: WebBundle:OurServices:dome }
web_our_services_sticker:
    pattern:  /nuestros-servicios/stickers-publicitarios
    defaults: { _controller: WebBundle:OurServices:sticker }
web_our_services_pad:
    pattern:  /nuestros-servicios/mouse-pads-personalizados
    defaults: { _controller: WebBundle:OurServices:pad }
    
# clients
web_clients:
    pattern:  /clientes
    defaults: { _controller: WebBundle:Clients:clients }
    
# portfolio
web_portfolio:
    pattern:  /portfolio
    defaults: { _controller: WebBundle:Portfolio:portfolio }