web_home:
    pattern:  /
    defaults: { _controller: WebBundle:Home:home }
web_about:
    pattern:  /nosotros
    defaults: { _controller: WebBundle:About:about }

# Our services
web_our_services:
    pattern:  /nuestros-servicios
    defaults: { _controller: WebBundle:OurServices:ourServices }
web_our_services_tshirt:
    pattern:  /nuestros-servicios/remeras-estampadas
    defaults: { _controller: WebBundle:OurServices:tshirt }
web_our_services_keychain_ribbon:
    pattern:  /nuestros-servicios/llaveros-cinta-publicitarios
    defaults: { _controller: WebBundle:OurServices:keychainRibbon }
web_our_services_keychain_poli:
    pattern:  /nuestros-servicios/llaveros-polimero-publicitarios
    defaults: { _controller: WebBundle:OurServices:keychainPoli }
web_our_services_cushion:
    pattern:  /nuestros-servicios/almohadones-publicitarios
    defaults: { _controller: WebBundle:OurServices:cushion }
